version: '3.8'
services:
 web:
  build: ./flask_app
  ports:
  - 8080:8080
  volumes:
  - ./:/app
  command: python3 app.py
  container_name: flasky
  depends_on:
    - db
 db:
  image: postgres:14-alpine
  restart: always
  ports:
  - 5432:5432
  environment:
  - POSTGRES_DB=apartments
  - POSTGRES_PASSWORD=ntkntk
  - POSTGRES_USER=postgres
  volumes:
   - post_data:/var/lib/postgresql/data
   - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  container_name: postgresdb
volumes:
  post_data:




